### ISSUE TITLE
'import initializer' overwrites train_data.txt

### ISSUE THREAD

**Issue by jarw2** [tcorodrigues/ActiveLearning#5]
OS: Windows 10 / miniconda

Running optimizer.py having added the yield column to init_files/train_data.txt file.

  File "optimizer.py", line 95, in <module>
    predictions = model2.predict(X2)
  File "C:\Users\Jacob\miniconda3\envs\LabMateML\lib\site-packages\sklearn\ensemble\_forest.py", line 766, in predict
    X = self._validate_X_predict(X)
  File "C:\Users\Jacob\miniconda3\envs\LabMateML\lib\site-packages\sklearn\ensemble\_forest.py", line 412, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "C:\Users\Jacob\miniconda3\envs\LabMateML\lib\site-packages\sklearn\tree\_classes.py", line 380, in _validate_X_predict
    X = check_array(X, dtype=DTYPE, accept_sparse="csr")
  File "C:\Users\Jacob\miniconda3\envs\LabMateML\lib\site-packages\sklearn\utils\validation.py", line 578, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "C:\Users\Jacob\miniconda3\envs\LabMateML\lib\site-packages\sklearn\utils\validation.py", line 60, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

NaNs were generated because in optimizer.py:

import initializer

leads to init_files/train_data.txt being overwritten with the 10 random experiments suggested by initializer.py, hence removing the added yield column. 

Line 87: df_train_corrected = train.iloc[:,:-1]

now removes final column which is parameter, NOT yield. Therefore NaNs appear and cannot optimize later.

**Comment by pykao** [comment]
Hi Jacob,

You are right. `import initializer` does overwrite the yield value in the `init_files/train_data.txt`. I solved this issue in the repository I forked and requested a pull request here. Hopefully, Dr. Tiago will accept my PR soon.

Best regards, 
Po-Yu

**Comment by pykao** [comment]
Hi Jacob,

I again made some changes and opened a pull request. If you are in a hurry, you can download it from my repository.

Best regards,
Po-Yu

**Comment by pykao** [comment]
Hi @jarw2 

tcorodrigues, Bundaberg-Joey and I updated the repository with a better interface and solved several bugs including the one you showed here. Please download the latest version of LabMate.ML. 

Let us know if you still have any issues. 

Best,
pykao

**Comment by jarw2** [comment]
Great, thanks for letting me know, I'll get the new version now.

Best,
Jacob
________________________________

**Comment by pykao** [comment]
Hi @jarw2 ,

Does the new version work for you know?

Best,
Ken

**Comment by jarw2** [comment]
Yes, thank you. It's no longer overwriting the file.

Best,
Jacob
________________________________
